apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: hello-trigger-binding
spec:
  params:
    - name: repository
      value: "https://github.com/tjungbauer/Tekton-Tutorial"
    - name: branch
      value: "master"
