apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: hello-listener
spec:
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: hello-trigger-binding
      template:
        ref: hello-trigger-template
